server:
  port: 9012

spring:
  application:
    name: customer-service
  servlet:
    context-path: /api/v1/rastech
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: rastech
    password: 1728394560
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        #hbm2ddl:
          #auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
