server:
  port: 8081

spring:
  application:
    name: fraud-application

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: rastech
    password: 1728394560
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        #hbm2ddl:
          #auto: update
    show-sql: true
